// Generates game/rivals.js: three bot-driven rival laps at different paces.
// Rivals replay through the same ghost pipeline as challenge rivals, so each
// is just a recorded run. Rerun after track or vehicle changes:
//   ./scripts/record-rivals.sh
import { writeFileSync } from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { createVehicleState, updateVehicle } from "./game/vehicle.js";
import { TRACK } from "./game/track.js";

const IDLE = { left: false, right: false, gas: false, brake: false, handbrake: false, boost: false };
const DT = 1 / 60;

// vmax caps straight-line speed (m/s) — the main difficulty dial; bias shifts
// the driven line off center so the pack doesn't run nose-to-tail.
const RIVALS = [
  { id: "tofu-taxi", name: "Tofu Taxi", color: "#27c0c9", vmax: 22, bias: 1.4 },
  { id: "drift-cat", name: "Drift Cat", color: "#ff7a1a", vmax: 33, bias: -1.2 },
  { id: "kaido-king", name: "Kaido King", color: "#8d4fd4", vmax: 999, bias: 0 },
];

function decimateGhost(samples, max) {
  if (samples.length <= max) return samples;
  const out = [];
  const step = (samples.length - 1) / (max - 1);
  for (let i = 0; i < max; i += 1) out.push(samples[Math.round(i * step)]);
  return out;
}

function driveRival({ vmax, bias }) {
  const car = createVehicleState();
  let frames = 0;
  while (car.lap < TRACK.laps && frames < 60 * 900) {
    const u = car.headingError + 0.08 * (car.lateral - bias);
    updateVehicle(
      car,
      { ...IDLE, gas: car.forwardSpeed < vmax, left: u > 0.04, right: u < -0.04 },
      DT,
    );
    frames += 1;
  }
  if (car.lap < TRACK.laps) throw new Error("rival bot failed to finish");
  return { timeMs: Math.round(car.timeMs), ghost: decimateGhost(car.ghost, 400) };
}

const runs = RIVALS.map((rival) => {
  const { timeMs, ghost } = driveRival(rival);
  console.log(`${rival.name}: ${(timeMs / 1000).toFixed(1)}s, ${ghost.length} samples`);
  return { id: rival.id, name: rival.name, color: rival.color, timeMs, ghost };
});

const round = (value) => Math.round(value * 100) / 100;
const compactGhost = (ghost) => ghost.map((s) => ({ t: Math.round(s.t), d: round(s.d), l: round(s.l), h: round(s.h) }));

const file = `// Generated by scripts/record-rivals.mjs — do not edit by hand.
// Three computer rivals for ${TRACK.id}, slow to fast. Each is a recorded bot
// run replayed through the ghost pipeline ({t,d,l,h} samples).
export const RIVAL_RUNS = ${JSON.stringify(
  runs.map((run) => ({ ...run, ghost: compactGhost(run.ghost) })),
)};
`;

// when run via record-rivals.sh this lands in the temp harness's game/ dir and
// the shell script copies it back into the repo
const out = path.join(path.dirname(fileURLToPath(import.meta.url)), "game", "rivals.js");
writeFileSync(out, file);
console.log(`wrote ${out}`);
